[package]
name = "aella-desktop"
version = "0.1.0"
edition = "2024"

[dependencies]
aella-core = { path = "../aella-core" }
harper-core = { workspace = true }
iced = { workspace = true, features = ["debug"] }
tokio = { workspace = true }
iced_core = "0.14.0"
image = "0.25.9"

[package.metadata.bundle]
name = "Aella"
identifier = "com.arkye03.aella"
icon = [
    "aella-desktop/assets/aella.icns",
    "aella-desktop/assets/aellaWindowsIcon.ico",
    "assets/aella.icns",
    "assets/aellaWindowsIcon.ico",
]
short_description = "Aella grammar checker"
category = "Productivity"
